
namespace: "fain_ansible_testing"
name: "ansible_collection_test"
version: "1.0.0"
readme: "README.md"
authors:
    - "Fain Street"
description: "testing ansible collection install from github repo"
